version: 2
dependencies:
  override:
    - mkdir -p ~/.go_project/src/github.com/${CIRCLE_PROJECT_USERNAME}
    - ln -s ${HOME}/${CIRCLE_PROJECT_REPONAME} ${HOME}/.go_project/src/github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: go get -u -v -t github.com/Masterminds/glide
      - run: glide install -v
      - run: go build
  release:
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: go get -u -v -t github.com/Masterminds/glide
      - run: glide install -v
      - run: curl -sL https://git.io/goreleaser | bash
workflows:
  version: 2
  build:
    jobs:
      - build
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
