version: 2
jobs:
  release:
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: go get -u -v -t github.com/Masterminds/glide
      - run: go get -u github.com/go-bindata/go-bindata/...
      - run: glide install -v
      - run: go-bindata -pkg assets -o assets/assets.go data/...
      - run: curl -sL https://git.io/goreleaser | bash
workflows:
  version: 2
  build:
    jobs:
      - release
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
